platform :ios, '7.0'

pod 'AFNetworking', '~> 2.0.3'
pod 'AXKCollectionViewTools', '~> 1.0'
pod 'Facebook-iOS-SDK', '~> 3.10'
pod 'JRSwizzle', '~> 1.0'
pod 'libextobjc', '~> 0.3'
pod 'ReactiveCocoa', '~> 2.1.8'
pod 'SDNetworkActivityIndicator', '~> 0.0.1'
pod 'SDWebImage', '~> 3.5'
pod 'Slash', '~> 0.1'
pod 'TransformerKit', '~> 0.3.0'
pod 'TestFlightSDK', '~> 2.2.0-noadid-beta'
