platform :ios, '7.0'

pod 'AFNetworking', '~> 2.2.1'
pod 'AXKCollectionViewTools', '~> 1.0.3'
pod 'AXKViewLayout', '~> 1.0.1'
pod 'Facebook-iOS-SDK', '~> 3.13.0'
pod 'FormatterKit', '~> 1.4.0'
pod 'Haneke', '~> 0.0.4'
pod 'JRSwizzle', '~> 1.0'
pod 'ReactiveCocoa', '~> 2.2.4'
pod 'SDNetworkActivityIndicator', '~> 0.0.1'
pod 'SDWebImage', '~> 3.5.4'
pod 'Slash', '~> 0.1.2'
pod 'TransformerKit', '~> 0.3.1'
pod 'TestFlightSDK', '~> 3.0.0'
